### ISSUE TITLE
Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by alanmels** [docksal/docksal#1205]
Creating a Drupal 7 website with `fin project create` command and switching to its CLI with `fin bash` gave the error:

```
 fin bash
path.js:1082
        path = process.cwd();
                       ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1082:24)
    at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:479:17)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:574:20)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /home/docker/.nvm/versions/node/v10.15.0/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/home/docker/.nvm/versions/node/v10.15.0/lib/node_modules/npm/bin/npm-cli.js:153:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v10.15.0 --silent` to unset it.
docker@cli:/var/www/docroot$ 
```

Just wanted to report the error, through everything seems to be working normally.

**Comment by lmakarov** [comment]
@alanmels please provide outputs from `fin config` and `fin sysinfo` as requested in the issue submission template. Without those it's very hard to diagnose the issue you experienced.

Note: I was not able to reproduce this with the current stable release of Docksal on a Linux instance:

```
$ fin project create
...
Project folder:   /root/projects/drupal7
Project software: Drupal 7
Project URL:      http://drupal7.docksal

Do you wish to proceed? [y/n]: y
Cloning repository...
...
Open http://drupal7 in your browser to verify the setup.
 DONE!  Completed all initialization steps.
[node1] (local) root@192.168.0.33 ~/projects
$ cd drupal7/
[node1] (local) root@192.168.0.33 ~/projects/drupal7
$ fin bash
docker@cli:/var/www$ 
```

**Comment by alanmels** [comment]
I believe this happened just because I had not restarted docker for really long time. After I've done it the same command didn't give any error. Please deem this as closed. Thanks.
