### ISSUE TITLE
NFS volumes broken with Docker Desktop using Virtualization Framework in macOS Big Sur

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#1477]
Docker Desktop added an experimental option to use the new [Virtualization Framework](https://developer.apple.com/documentation/virtualization) available in macOS Big Sur.

On an Intel Mac, users can choose between a HyperKit and a Virtualization Framework VM.

![image](https://user-images.githubusercontent.com/1205005/111852914-17497100-88d6-11eb-9990-4194dd938f4f.png)

On a M1 Mac, Virtualization Framework is the only option.
https://docs.docker.com/docker-for-mac/apple-m1/

When using Virtualization Framework, NFS volumes a broken:

```
❯ fin init
Removing containers...
Removing test_cli_1 ... done
Removing test_db_1  ... done
Removing network test_default
Removing volume test_cli_home
Removing volume test_project_root
Removing volume test_db_data
Volume docksal_ssh_agent is external, skipping
Starting services...
Creating network "test_default" with the default driver
Creating volume "test_cli_home" with default driver
Creating volume "test_project_root" with local driver
Creating volume "test_db_data" with default driver
Creating test_cli_1 ... 
Creating test_db_1  ... error

Creating test_cli_1 ... error
Work/Labs/docksal/test:/var/lib/docker/volumes/test_project_root/_data, flags: 0xc00, data: addr=192.168.64.1,vers=3,nolock,noacl,nocto,actimeo=1: permission denied

ERROR: for test_cli_1  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/test_project_root/_data': failed to mount local volume: mount :/Users/leonid/Work/Labs/docksal/test:/var/lib/docker/volumes/test_project_root/_data, flags: 0xc00, data: addr=192.168.64.1,vers=3,nolock,noacl,nocto,actimeo=1: permission denied

ERROR: for db  Cannot start service db: error while mounting volume '/var/lib/docker/volumes/test_project_root/_data': failed to mount local volume: mount :/Users/leonid/Work/Labs/docksal/test:/var/lib/docker/volumes/test_project_root/_data, flags: 0xc00, data: addr=192.168.64.1,vers=3,nolock,noacl,nocto,actimeo=1: permission denied

ERROR: for cli  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/test_project_root/_data': failed to mount local volume: mount :/Users/leonid/Work/Labs/docksal/test:/var/lib/docker/volumes/test_project_root/_data, flags: 0xc00, data: addr=192.168.64.1,vers=3,nolock,noacl,nocto,actimeo=1: permission denied
ERROR: Encountered errors while bringing up the project.
```

**Comment by lmakarov** [comment]
The two Docker Desktop virtualization modes on macOS have different networking setup.

Docker Desktop HK (HyperKit):

```
❯ docker run --rm -it --privileged --pid=host alpine nsenter -t 1 -m -u -i -n -p -- ip addr show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:50:00:00:00:01 brd ff:ff:ff:ff:ff:ff
    inet 192.168.65.3/24 brd 192.168.65.255 scope global dynamic noprefixroute eth0
       valid_lft 7179sec preferred_lft 5739sec
    inet6 fe80::50:ff:fe00:1/64 scope link 
       valid_lft forever preferred_lft forever
```

Docker Desktop VF (Virtualization Framework)

```
❯ docker run --rm -it --privileged --pid=host alpine nsenter -t 1 -m -u -i -n -p -- ip addr show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether d2:29:e4:4d:a6:39 brd ff:ff:ff:ff:ff:ff
    inet 192.168.81.8/24 brd 192.168.81.255 scope global dynamic noprefixroute eth0
       valid_lft 84201sec preferred_lft 73509sec
    inet6 fe80::d029:e4ff:fe4d:a639/64 scope link 
       valid_lft forever preferred_lft forever
```

Interestingly, requests from VM/containers originate from different IPs:

- Docker Desktop HK: `127.0.0.1` (or `192.168.64.100` when Docksal is running, since we assign this IP as an alias on the `lo0` interface)
- Docker Desktop VF: `192.168.81.8`

The way we currently set up NFS shares only allows access from `192.168.64.1` and `192.168.64.100`.

```
❯ cat /etc/exports

# <ds-nfs docksal
/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
```

As `192.168.81.8` is a dynamic IP, we'd have to configure NFS shares this way for Docker Desktop VF:

```
/Users -network 192.168.81.0 -mask 255.255.255.0 -alldirs -maproot=0:0
```

macOS does not allow specifying both IP(s) and network/mask at the same time, so this would need to be done dynamically based on what mode Docker Desktop is configured to use.

**Comment by lmakarov** [comment]
Apparently, this works on Mac:

```
❯ cat /etc/exports

# <ds-nfs docksal
/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
/Users -network 192.168.81.0 -mask 255.255.255.0 -alldirs -maproot=0:0
# ds-nfs>
```

It translates into:

```
❯ showmount -e
Exports list on localhost:
/Users                              192.168.81.0 192.168.64.1 192.168.64.100
```

However, this does not work as expected (not a replacement for -network ... -mask ...):

```
/Users 192.168.81.0 -alldirs -maproot=0:0
```

**Comment by alanmels** [comment]
I've hit the following error lines today when trying to get docksal work on MacBook Pro with M1 chip:

```
Digest: sha256:db6817bc62bdd93cff38e514f28627d364ff157572be59c3a2a98df399b352aa
Status: Downloaded newer image for docksal/cli:2.11-php7.3
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x4cb21f, 0x9)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.newosproc(0xc42002c000, 0xc42003bfc0)
	/usr/local/go/src/runtime/os_linux.go:160 +0x194
runtime.newm(0x4d6db8, 0x0)
	/usr/local/go/src/runtime/proc.go:1572 +0x132
runtime.main.func1()
	/usr/local/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x53ae00)
	/usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420026768 sp=0xc420026760
runtime.main()
	/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200267c0 sp=0xc420026768
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200267c8 sp=0xc4200267c0
Checkout finished with errors. Do you wish to continue with project init? [y/n]: 
```

Is it the same issue and I should try to suggested change, or should I create a separate error report?
