### ISSUE TITLE
Cannot run `fin drupal`

### ISSUE THREAD

**Issue by MKorostoff** [docksal/docksal#33]
To reproduce:

# Problem
1. Download the [drupal 8 sample project](https://github.com/docksal/drupal8).
1. Run `fin init`
1. Open your browser, and see that drupal has installed successfully
1. Change directory into your drupal docroot
1. Run `fin drupal`
1. See that you get the following error:

```
[11-Nov-2016 17:19:27 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: The directory "/home/docker/.console/cache/annotations" does not exist and could not be created. in phar:///usr/local/bin/drupal/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php:86
Stack trace:
#0 phar:///usr/local/bin/drupal/src/Annotations/CacheFactory.php(15): Doctrine\Common\Annotations\FileCacheReader->__construct(Object(Doctrine\Common\Annotations\AnnotationReader), '/home/docker/.c...', false)
#1 [internal function]: Drupal\Console\Annotations\CacheFactory::createFileCache(Object(Doctrine\Common\Annotations\AnnotationReader), Object(Drupal\Console\Config))
#2 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(905): call_user_func_array(Array, Array)
#3 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(475): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'annotation_file...')
#4 phar:///us in phar:///usr/local/bin/drupal/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php on line 86
```

# Workaround
1. ssh into your container by running `fin bash`
1. Once inside the container, run the following:

```
sudo mkdir -p /home/docker/.console/cache/annotations
sudo chmod -R 777 /home/docker/.console/
```
3. Exit the docker container
4. run `fin drupal`
5. See that drupal console now executes successfully

**Comment by david-hernandez** [comment]
What version of fin are you using? Just adding that I am on 0.9.0 after an update and it is working fine on a new project.

**Comment by MKorostoff** [comment]
@david-hernandez I am running 0.6.5.  I will try 0.9.0 and report back with my results.

**Comment by lmakarov** [comment]
@MKorostoff you may want to pull the latest docksal/drupal8 codebase and then do update Docksal. In your case the update steps would be:

```
fin update self
fin update
```
`/home/docker/.console/cache` is now cleaned up in the most recent php7 version of the cli image.

**Comment by MKorostoff** [comment]
Hello all, I have updated to the latest version of docksal (0.11.6) and I am no longer experiencing this for Drupal 8.  I am however experiencing this for Drupal 7 (which I never attempted with fin v0.6.5, so I don't know if it worked before upgrading).

**Comment by achekulaev** [comment]
I actually myself have an issue with Drupal console
```
$ fin drupal
[02-Dec-2016 20:14:53 UTC] Recoverable fatal error: Argument 1 passed to Drupal\metatag\Command\GenerateGroupCommand::__construct() must be an instance of Drupal\metatag\Generator\MetatagGroupGenerator, none given in /var/www/docroot/modules/contrib/metatag/src/Command/GenerateGroupCommand.php on line 57 #0 /var/www/docroot/core/includes/bootstrap.inc(548): _drupal_error_handler_real(4096, 'Argument 1 pass...', '/var/www/docroo...', 57, Array)
#1 /var/www/docroot/modules/contrib/metatag/src/Command/GenerateGroupCommand.php(57): _drupal_error_handler(4096, 'Argument 1 pass...', '/var/www/docroo...', 57, Array)
#2 [internal function]: Drupal\metatag\Command\GenerateGroupCommand->__construct()
#3 phar:///usr/local/bin/drupal/src/Helper/CommandDiscoveryHelper.php(282): ReflectionClass->newInstance()
#4 phar:///usr/local/bin/drupal/src/Helper/CommandDiscoveryHelper.php(220): Drupal\Console\Helper\CommandDiscoveryHelper->validateCommand('Drupal\\metatag\\...', 'metatag', 'module')
#5 phar:///usr/local/bin/drupal/src/Helper/CommandDiscoveryHelper.php(159): Drupal\Console\Helper\CommandDiscoveryHelper->extractCommands('/var/www/docroo...', 'metatag', 'module')
#6 phar:///usr/local/bin/drupal/src/Helper/CommandDiscoveryHelper.php(117): Drupal\Console\Helper\CommandDiscoveryHelper->discoverCommands(Array)
#7 phar:///usr/local/bin/drupal/src/Helper/CommandDiscoveryHelper.php(75): Drupal\Console\Helper\CommandDiscoveryHelper->getCustomCommands()
#8 phar:///usr/local/bin/drupal/src/Application.php(312): Drupal\Console\Helper\CommandDiscoveryHelper->getCommands()
#9 phar:///usr/local/bin/drupal/src/Application.php(245): Drupal\Console\Application->prepare(Object(Drupal\Console\Helper\DrupalHelper), NULL)
#10 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(123): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///usr/local/bin/drupal/bin/drupal.php(115): Symfony\Component\Console\Application->run()
#12 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#13 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#14 {main}
Recoverable fatal error: Argument 1 passed to Drupal\metatag\Command\GenerateGroupCommand::__construct() must be an instance of Drupal\metatag\Generator\MetatagGroupGenerator, none given in Drupal\metatag\Command\GenerateGroupCommand->__construct() (line 57 of /var/www/docroot/modules/contrib/metatag/src/Command/GenerateGroupCommand.php).
15:14:53 Alexeis-MacBook-Pro-2016 /Users/alexei.chekulaev/Projects/netscout/docroot
```

**Comment by lmakarov** [comment]
@MKorostoff I pushed a fix for the original issue and it's available in the `docksal/cli:1.0-php7` image (used by docksal/drupal8). For php5 it's only available via `docksal/cli:latest`, but not has not been released yet in `docksal/cli:1.0-php5` (used by docksal/drupal7).

**Comment by lmakarov** [comment]
@achekulaev 
> I actually myself have an issue with Drupal console

Update to the latest dev version of metatag.

**Comment by MKorostoff** [comment]
Solved! After I ran `fin up` I no longer have this issue.

**Comment by MKorostoff** [comment]
Thanks @lmakarov

**Comment by achekulaev** [comment]
> Update to the ... dev version
Ah, the Drupal 8 way...
