### ISSUE TITLE
Windows 10 Setup issue

### ISSUE THREAD

**Issue by justinlevi** [docksal/docksal#531]
----------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**When I try and run an fin command, I get the following error**

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_eng                            ine: The system cannot find the file specified. In the default daemon configuration on Windows, the                             docker client must be run elevated to connect. This error may also indicate that the docker daemon i                            s not running.
```

**Steps to reproduce the issue:**

1. Go through the Docker native steps here  : http://docksal.readthedocs.io/en/master/getting-started/env-setup-native/
2. run the curl command `curl -fsSL https://get.docksal.io | sh`

**Describe the results you received:**

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_eng                            ine: The system cannot find the file specified. In the default daemon configuration on Windows, the                             docker client must be run elevated to connect. This error may also indicate that the docker daemon i                            s not running.
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_eng                            ine: The system cannot find the file specified. In the default daemon configuration on Windows, the                             docker client must be run elevated to connect. This error may also indicate that the docker daemon i                            s not running.
[STEP 1/4] Updating fin... 1.52.0 [OK]
[STEP 2/4] Updating stack files...
overrides-osxfs.yml
services.yml
stack-acquia.yml
stack-default.yml
stack-default-nodb.yml
stack-node.yml
volumes-bind.yml
volumes-nfs.yml
volumes-unison.yml
[STEP 3/4] Updating tools...
Installing winpty v0.4.3...
Downloading winpty-0.4.3-cygwin-2.8.0-ia32.tar.gz...
######################################################################## 100.0%
Going to optimize Windows network settings for file sharing...
You may see an elevated command prompt - click Yes.
Adjusting git defaults...
git config --global core.autocrlf input
git config --system core.longpaths true
[STEP 4/4] Updating system images...
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_eng                            ine: The system cannot find the file specified. In the default daemon configuration on Windows, the                             docker client must be run elevated to connect. This error may also indicate that the docker daemon i                            s not running.
 ERROR:  Your Docker client is unable to talk to the Docker server.
         WHAT TO DO?
         Check that your Docker for Mac/Win app is running.
{ ~ }  » fin system reset                                                                     ~ 1
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_eng                            ine: The system cannot find the file specified. In the default daemon configuration on Windows, the                             docker client must be run elevated to connect. This error may also indicate that the docker daemon i                            s not running.
Resetting network settings...
Resetting Docksal services...
 * proxy
C:\Users\JWinter\.babun\cygwin\home\JWinter\.docksal\bin\docker.exe: error during connect: Post http                            ://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/containers/create?name=docksal-vhost-proxy: open //./pipe/do                            cker_engine: The system cannot find the file specified. In the default daemon configuration on Windo                            ws, the docker client must be run elevated to connect. This error may also indicate that the docker                             daemon is not running.
See 'C:\Users\JWinter\.babun\cygwin\home\JWinter\.docksal\bin\docker.exe run --help'.
 * dns and resolver for .docksal domain
C:\Users\JWinter\.babun\cygwin\home\JWinter\.docksal\bin\docker.exe: error during connect: Post http                            ://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/containers/create?name=docksal-dns: open //./pipe/docker_eng                            ine: The system cannot find the file specified. In the default daemon configuration on Windows, the                             docker client must be run elevated to connect. This error may also indicate that the docker daemon i                            s not running.
See 'C:\Users\JWinter\.babun\cygwin\home\JWinter\.docksal\bin\docker.exe run --help'.
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 * ssh-agent
C:\Users\JWinter\.babun\cygwin\home\JWinter\.docksal\bin\docker.exe: error during connect: Post http                            ://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/containers/create?name=docksal-ssh-agent: open //./pipe/dock                            er_engine: The system cannot find the file specified. In the default daemon configuration on Windows                            , the docker client must be run elevated to connect. This error may also indicate that the docker da                            emon is not running.
See 'C:\Users\JWinter\.babun\cygwin\home\JWinter\.docksal\bin\docker.exe run --help'.
 ERROR:  docksal-ssh-agent is not running
         Please report this issue, as this should not usually happen.
         Run fin system reset ssh-agent to start the service.
```

**Describe the results you expected:**

No errors

**Output of `fin config`:**

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
 ERROR:  Cannot detect project root.
         Please make sure you have .docksal directory in the root of your project.
         To setup a basic Docksal stack in the current directory run fin config generate

```

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  { ~ }  » fin sysinfo                                                                                                      ~ 1
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
███  OS
 Microsoft Windows [Version 10.0.15063]
CYGWIN_NT-10.0-WOW W2UA7502F8C 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
Mode: Docker for Windows

███  FIN
fin version: 1.52.0

███  ENVIRONMENT
DOCKER_HOST             |
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

███  DOCKER INFO
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
███  DOCKER COMPOSE
EXPECTED VERSION: 1.19.0
docker-compose version 1.21.1, build 7641a569
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine.exe version 0.14.0, build 89b8332

NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

███  HDD Usage
Caption  FreeSpace      Size
C:       194366910464   255086030848
D:       999846891520   1000068870144
E:
O:       6011164360704  24739011624960


███  RAM Usage
find: ‘Available Physical Memory’: No such file or directory

███  RAM Usage per container
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

  ```

</details>

**Comment by justinlevi** [comment]
Not sure if it helps or not, but I'm also seeing this error when trying to install Lando and their stable version of docker.
![dockerinstall](https://user-images.githubusercontent.com/1117989/40068359-6fc49e64-5836-11e8-8e7d-3ef1f5c1d484.PNG)


```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation failed.

An unexpected error occurred: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).

The operation failed.

The Hyper-V Virtual Machine Management service encountered an unexpected error: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).
at New-MobyLinuxVM, <No file>: line 187
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```
