### ISSUE TITLE
Docker has disk issues sporadically

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#622]
```
§ fin p create
             -= Docksal project wizard =-
1. Name your project (lowercase alphanumeric, underscore, and hyphen): drupal8
2. What would you like to install?
  PHP based
    1.  Drupal 8
    2.  Drupal 7
    3.  Wordpress
    4.  Magento
    5.  Laravel
    6.  Symfony Skeleton
    7.  Symfony WebApp
    8.  Grav CMS
    9.  Backdrop CMS
  JS based
    10. Hugo
    11. Gatsby JS
  HTML
    12. Static HTML site
Enter your choice (1-12): 1
Your site will be created at /Users/oleksii_chekulaiev/Projects/drupal8
Your site will run Drupal 8
The URL of your site will be http://drupal8.docksal
Do you wish to proceed? [y/n]: y
Cloning repository...
Cloning into 'drupal8'...
remote: Counting objects: 51953, done.
remote: Compressing objects: 100% (811/811), done.
remote: Total 51953 (delta 311), reused 588 (delta 220), pack-reused 50891
Receiving objects: 100% (51953/51953), 30.59 MiB | 7.32 MiB/s, done.
Resolving deltas: 100% (23543/23543), done.
3. Installing site
 Step 1  Initializing stack...
Removing containers...
Removing network drupal8_default
Removing volume drupal8_project_root
WARNING: Volume drupal8_project_root not found.
Volume docksal_ssh_agent is external, skipping
Identity added: id_rsa (id_rsa)
Starting services...
Creating network "drupal8_default" with the default driver
Creating volume "drupal8_project_root" with local driver
Creating drupal8_cli_1 ... done
Creating drupal8_db_1  ... done
Creating drupal8_web_1 ... done
Waiting for drupal8_cli_1 to become ready...
Connected vhost-proxy to "drupal8_default" network.
Waiting 10s for MySQL to initialize...
 Step 2  Initializing site...
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
path.js:1167
          cwd = process.cwd();
                        ^
Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1167:25)
    at Function.Module._resolveLookupPaths (module.js:424:17)
    at Function.Module._resolveFilename (module.js:541:20)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/bin/npm-cli.js:145:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v8.11.0 --silent` to unset it.
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
bash: /var/www/.docksal/commands/init-site: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

**Comment by lmakarov** [comment]
@achekulaev you should include your `fin sysinfo` ;)
I assume this is on Docker for Mac specific?

**Comment by achekulaev** [comment]
Yes it seems to be Docker for Mac specific. There is nothing interesting in `sysinfo` really. 
It happens sporadically. Usually after computer wake. 
Daemon restart fixes the issue. 
Started happening since update to 18.03

**Comment by pthurmond** [comment]
I am seeing this on a Linux server as well.

**Comment by lmakarov** [comment]
@pthurmond are you able to identify any pattern for this behavior on Linux?
