### ISSUE TITLE
run-cli does not work in alpine from /root folder

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#661]
If you try `fin run-cli` on Play with Docker inside `/root` folder you will get a nasty error. Which actually means that Docksal should not be at all used from the root folder, because `docker` user does not have access to that folder.

```bash
$ fin run-cli ls
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Error: EACCES: permission denied, scandir '/var/www'
(node:329) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at errorHandler (/home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/bin/npm-cli.js:76:20
    at cb (/home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/lib/npm.js:228:22)
    at /home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/lib/npm.js:266:24
    at /home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at /home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/lib/config/core.js:112:20
    at <anonymous>
(node:329) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either bythrowing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:329) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
TypeError: Cannot read property 'loaded' of undefined
    at process.<anonymous> (/home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/lib/utils/error-handler.js:40:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
/home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/home/docker/.nvm/versions/node/v8.11.0/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:375:26)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v8.11.0 --silent` to unset it.
ls: cannot open directory '.': Permission denied
[node1] (local) root@192.168.0.48 ~
$
```

Not sure what to do with it apart from just documenting here.

**Comment by lmakarov** [comment]
`docksal/cli` set permissions on `/var/www` (non-recursive) at startup:

https://github.com/docksal/service-cli/blob/43661762ff3f6b957f3a2330a85f5760a65c745e/7.1/startup.sh#L92-L94

`/var/www` inside cli maps to `/root` in this case and `cli` tries to do `chown 1000:1000` on it.
It does not look like that operation fails actually, as there is no visible error. Though, permissions don't seem to be set in the end and an error is thrown later on:

```
$ fin rc --debug
 ALERT:  Running as root is not recommended
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
2018-06-29 17:35:55 | Rendering template: /home/docker/.ssh/id_rsa.tmpl...
2018-06-29 17:35:56 | Rendering template: /home/docker/.acquia/cloudapi.conf.tmpl...
2018-06-29 17:35:56 | Resetting permissions on /home/docker and /var/www...
2018-06-29 17:35:56 | Preliminary initialization completed
2018-06-29 17:35:56 | Executing the requested command...
Error: EACCES: permission denied, scandir '/var/www'
```

Doing `chown 1000:1000 /var/www` inside `run-cli` or `chown 1000:1000 /root` on the host addresses the issue.

Worth noting, that this will only happen when running as root, which we do not recommend anyway.

For the disposable PWD environments, where there is no choice, we can either prevent users from running `run-cli` in `/root` (`$HOME`) or silently do `chown 1000:1000 /root` and call it done :trollface:
