### ISSUE TITLE
issue with fin start

### ISSUE THREAD

**Issue by sean-e-dietrich** [docksal/docksal#754]
steps to reproduce

```
mkdir testproject
cd testproject
mkdir .docksal
fin start
```

I get the following error

```
➜  testproject fin start
Starting services...
Pulling cli (docksal/cli:2.4-php7.1)...
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1052, in up
  File "compose/cli/main.py", line 1048, in up
  File "compose/project.py", line 466, in up
  File "compose/service.py", line 339, in ensure_image_exists
  File "compose/service.py", line 1163, in pull
  File "site-packages/docker/api/image.py", line 380, in pull
  File "site-packages/docker/auth.py", line 47, in get_config_header
  File "site-packages/docker/auth.py", line 94, in resolve_authconfig
  File "site-packages/docker/auth.py", line 124, in _resolve_authconfig_credstore
  File "site-packages/dockerpycreds/store.py", line 23, in __init__
dockerpycreds.errors.InitializationError: docker-credential-osxkeychain not installed or not available in PATH
[49619] Failed to execute script docker-compose
```

**Comment by sean-e-dietrich** [comment]
Issue was due to left over docker for mac issue. Removed line in `~/.docker/config.json`

```
        "credsStore": "osxkeychain"
```
